name: Compile U-Boot

on:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: debian:buster

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up toolchain
              run: |
                apt-get update
                apt-get install -y build-essential git flex bison wget

            - name: Download OpenWrt 14.07 SDK
              run: |
                wget -O /tmp/sdk.tar.bz2 https://archive.openwrt.org/barrier_breaker/14.07/mpc85xx/p1020/OpenWrt-SDK-mpc85xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2 
            
            - name: Extract OpenWrt 14.07 SDK
              run: |
                tar xf /tmp/sdk.tar.bz2 -C /tmp
            
            - name: Create Config
              run: |
                make P1020RDB-PD_NAND_config
              
            - name: Compile U-Boot
              run: make CROSS_COMPILE="/tmp/OpenWrt-SDK-mpc85xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/staging_dir/toolchain-powerpc_8540_gcc-4.8-linaro_uClibc-0.9.33.2/bin/powerpc-openwrt-linux-"

            - name: List Output Folder
              run: ls -la

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: u-boot
                path: u-boot.bin
